### PR TITLE
[MRG] Getting-Started Notebook

### PR DESCRIPTION
**Pull request by bhargavvader**
@dustinvtran, this is with respect to #35.

This is just the getting started - "First Edward Program" done in a notebook format.
It combines both the source code and the webpage's material.

Do let me know if this is fine, I'll try and do the same for all the other tutorials and example programs.

### CODE REVIEW

**Comment by bhargavvader** [comment]
@dustinvtran, what's up with the `Coverage` check? Why is it still pending?

Would also like a review of this when you can, so I can start working on the other tutorial notebooks. :)

**Comment by dustinvtran** [comment]
Looks great! Do you have a suggestion of where to link to these? My guess is that if there's an iPython notebook for each example, we can add a sentence which links to this `docs/notebooks` directory in the main Tutorials page.

**Comment by bhargavvader** [comment]
Yeah, that sounds good! 
I also haven't verified this yet - but do all the `examples` feature in the tutorials section?
Or are there some python files in `example` which do not have tutorials written up?

**Comment by dustinvtran** [comment]
Yeah quite a few python files in the `examples/` directory do not have a tutorial. For now I guess it makes sense to only feature iPython notebooks for examples that have tutorials. (Examples that don't have tutorials are more raw/bleeding edge and are likely to change.)

**Comment by bhargavvader** [comment]
Okay, cool. :)
Feel free to merge this now if you think it is fine. 

I'll get around to doing the same for the other tutorials as well, and maybe make some 'temporary' notebooks for the example files which don't have tutorials written up, so it can maybe serve as a way to write the tutorials for those, and serve as a prototype (and also helps me in understanding edward better when I do this).

**Pull request merged**
