### PR TITLE
add note on conda

### PR DESCRIPTION
**Pull request by maedoc**
cf #321

### CODE REVIEW

**Comment by dustinvtran** [comment]
lgtm

**Comment by dustinvtran** [comment]
oh. can you submit a PR merging these changes to `master`? the `gh-pages` is a branch purely for deployment purposes. [details here](https://github.com/blei-lab/edward/tree/master/docs)

**Comment by maedoc** [comment]
just rebase master on this branch and push?

**Comment by dustinvtran** [comment]
`gh-pages` and `master` have very different files and revision history.

**Pull request merged**
