### PR TITLE
support copying of/backprop through control flow

### LINKED ISSUE #525: Copied recursive graphs cannot be differentiated
After copying the graph of recursive variables, it cannot be differentiated. A Minimal example is:

```python
In [1]: import edward as ed

In [2]: import tensorflow as tf

In [3]: get_grads = lambda tensor: tf.gradients(tensor, [v._ref() for v in ed.get_variables(tensor)])

In [4]: cumsum = lambda tensor: tf.scan(lambda a, x: a + x, tensor)

In [5]: a = tf.Variable([1.0, 2.0, 3.0])

In [6]: get_grads(2 * a)
Out[6]: [<tf.Tensor 'gradients_2/mul_2_grad/Reshape_1:0' shape=(3,) dtype=float32>]

In [7]: get_grads(ed.copy(2 * a))
Out[7]: [<tf.Tensor 'gradients_3/copied/mul_3_grad/Reshape_1:0' shape=(3,) dtype=float32>]

In [8]: get_grads(cumsum(a))
Out[8]: [<tf.Tensor 'gradients_4/scan/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3:0' shape=(3,) dtype=float32>]

In [9]: get_grads(ed.copy(cumsum(a)))
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-713dbebd9b76> in <module>()
----> 1 get_grads(ed.copy(cumsum(a)))

<ipython-input-7-a19aa9ea108c> in <lambda>(tensor)
----> 1 get_grads = lambda tensor: tf.gradients(tensor, [v._ref() for v in ed.get_variables(tensor)])

/Volumes/Home/venvs/py3-data-science/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py in gradients(ys, xs, grad_ys, name, colocate_gradients_with_ops, gate_gradients, aggregation_method)
    392     pending_count, loop_state = _PendingCount(ops.get_default_graph(), to_ops,
    393                                               from_ops,
--> 394                                               colocate_gradients_with_ops)
    395 
    396     # Iterate over the collected ops.

/Volumes/Home/venvs/py3-data-science/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py in _PendingCount(graph, to_ops, from_ops, colocate_gradients_with_ops)
    184   # 'loop_state' is None if there are no while loops.
    185   loop_state = control_flow_ops.MaybeCreateControlFlowState(
--> 186       between_op_list, between_ops, colocate_gradients_with_ops)
    187 
    188   # Initialize pending count for between ops.

/Volumes/Home/venvs/py3-data-science/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py in MaybeCreateControlFlowState(between_op_list, between_ops, colocate_gradients_with_ops)
   1293           loop_state.AddWhileContext(op, between_op_list, between_ops)
   1294       else:
-> 1295         loop_state.AddWhileContext(op, between_op_list, between_ops)
   1296   return loop_state
   1297 

/Volumes/Home/venvs/py3-data-science/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py in AddWhileContext(self, op, between_op_list, between_ops)
   1102     if grad_state is None:
   1103       # This is a new while loop so create a grad state for it.
-> 1104       outer_forward_ctxt = forward_ctxt.outer_context
   1105       if outer_forward_ctxt:
   1106         outer_forward_ctxt = outer_forward_ctxt.GetWhileContext()

AttributeError: 'NoneType' object has no attribute 'outer_context'
````

At least on difference is the missing `_control_flow_context`:

```python
In [10]: get_exit_context = lambda tensor: tensor.op.inputs[2].op._control_flow_context

In [11]: get_exit_context(cumsum(a))
Out[11]: <tensorflow.python.ops.control_flow_ops.WhileContext at 0x11c87e160>

In [12]: get_exit_context(ed.copy(cumsum(a))) is None
Out[12]: True
```

### PR DESCRIPTION
**Pull request by jmxpearson**
- Closes #525 
- passes test in [this branch](https://github.com/blei-lab/edward/compare/bugfix/issue-525)
- adds test for nested control flow

### CODE REVIEW

**Comment by dustinvtran** [comment]
Cool that you got this to work! Have you tried this on any end-to-end examples? Do you think these unit tests are sufficient?

**Comment by jmxpearson** [comment]
We don't have an integration test in-house, but I think I can cobble together something from what others mentioned in #525. Right now, there are only two `ControlFlowContext` subclasses, and I think both are hit by the tests. Let me try to get a working full model going...

**Comment by jmxpearson** [comment]
I’m thinking this could just be tested with a simple AR(1) defined using `scan`. MAP inference calls `copy`, so this should fail on current `master`. Would a notebook with this example suffice?

Tomorrow is a bit busy, but I should be able to get it done over the weekend, if that’s not too late.

**Comment by dustinvtran** [comment]
AR(1) works. Logistically, a notebook is recommended only if you add quite a bit of text. Otherwise, a Python script is recommended.

re:weekend. Sure.

**Comment by dustinvtran** [comment]
Is this ready for me to take a look at? (Please ping me when. :)

**Comment by jmxpearson** [comment]
Yes. Please do.

**Comment by dustinvtran** [comment]
This is excellent work. No comments/todos needed. (I have no better suggestion for that collection business unfortunately.) Thanks again!

**Comment by chmp** [comment]
@jmxpearson 👍 Thanks a lot for the fix. I am really looking forward to give it a spin. :)

**Pull request merged**
