### PR TITLE
doc/website

### PR DESCRIPTION
**Pull request by akucukelbir**
#### Summary:

This PR does three things:

1. it introduces a brand-new website to replace the current one (via a custom `pandoc` workflow).
2. it introduces automatic API documentation (via `sphinx`).

There are a few remaining tasks before we can merge this:

- [x] figure out what goes into `deploy.sh`
- [x] finalize getting started / delving in / tutorials
- [x] update `README.md` to match website and updated logo

#### How to Verify:

Look at the website and check for issues/typos.

Look at docstrings and how they render via sphinx.

#### Side Effects:

The old website is deleted.

#### Documentation:

There is a new `README.md` under `/website` that documents the scripts that build and deploy the website

### CODE REVIEW

**Comment by dustinvtran** [comment]
The website looks essentially done. What else is left?

+ restructuring some of the model pages in the tutorials
+ filling in some of the end-to-end pages
+ update README.md
+ figure out what goes into deploy.sh

Anything else? I can work on the first one most immediately.

**Comment by dustinvtran** [comment]
1+2 done. @alp says 4 is done.

3 is remaining. Also I need to make some additional changes to the standalone API pages.

**Comment by akucukelbir** [comment]
- [ ] edit maja's tutorial to match style of rest of website
- [ ] dustin's remaining changes to standalone API pages

**Comment by mariru** [comment]
I edited the latent space models tutorial to be more similar in style to the other model tutorials.

**Comment by akucukelbir** [comment]
@mariru thank you! 
however, for some reason when you compile the website on your end, a bunch of the api/sphinx/pandoc configurations are being mis-calculated.
could you confirm that you have an up-to-date installation of the required packages?
they are described here: https://github.com/blei-lab/edward/blob/doc/website/website/README.md

**Comment by mariru** [comment]
I'd suggest that in the model in `getting_started.html` we add 
```def __init__(N): 
self.n_vars = N```
to the model definition because `n_vars` needs to be specified for any working model.

**Comment by dustinvtran** [comment]
actually, `n_vars` is only required at the moment for MAP estimation (and by extension, Laplace) :)

**Comment by dustinvtran** [comment]
Hi @akucukelbir. Before I touch the standalone pages, can you make sure they are the latest version available from the standalone pages branch?  (for example, the criticism page is out of date) This will help prevent later conflicts.

**Comment by akucukelbir** [comment]
@dustinvtran please work directly on the rst files in this branch. i had to manually convert parts of those markdown files to make sphinx happy. let's delete the standalone-pages branch asap.

**Comment by akucukelbir** [comment]
@mariru @dustinvtran i'm releasing all tokens. here's a mental list of things remaining

- [ ] maja's tutorial somehow disappeared from `tutorials.tex`
- [ ] wrap up standalone pages
- [ ] delete `doc/standalone-pages` branch
- [ ] merge this branch and run `./deploy.sh`

**Comment by dustinvtran** [comment]
Cool, deleting branch now and working on standalone pages. I moved Maja's tutorial to the end-to-end examples because it goes through the whole process and motivates from neuroscience data.

**Comment by dustinvtran** [comment]
@akucukelbir:
+ README.md
  + I propose changing image url to point to a github source storing the file
  + Following Dave, I always use `__word__` instead of `**word**` and + instead of - for bullet points. I propose we not change this for now, and we can discuss it in another pull request focusing on formatting changes; this pull request can focus strictly on website changes.
  + Where do we place backend features? I know the deep learning community for example would rarely touch probabilistic software because there is never support for GPUs or distributed training for truly scaling computation to massive data sets. And it's a massive distinguishing factor from other software, specifically other probabilistic programming libraries that don't often think about these issues.

    I propose after the criticism list, we should add the following sentence:
    ```Edward is built on top of [TensorFlow](https://www.tensorflow.org) as a backend, enabling features such as computational graphs, distributed training, CPU/GPU integration, automatic differentiation, and TensorBoard.```
  + Somewhere we need a link to the website. I think I agree with you that much of the information in the README.md is unnecessary, especially for a first-time reader. I propose we follow what TensorFlow's README.md does.

    That is, cut everything down from (and including) the __Authors__ section; then add
    ```
    ### Resources
    + [Edward website](http://edwardlib.org)
    ```
    This bulleted list will eventually include the white paper, our own model zoo, and other things.
+ examples/getting_started_example.py
  + This needs to be edited following the other bayesian NN scripts. For example, new data API using a dictionary for the data, `n_vars` and `n_layers`, `self.weight_dims = list(zip(...)))` for Python 3 support. Maybe it's as easy and re-copying and pasting the BayesianNN class and `build_toy_dataset()` from the other scripts.
+ getting-started.tex
  + let's remove the x=y line in the plots, which can be distracting

@mariru:
+ inferences.py
  + Trailing whitespace is the devil. Whenever pushing, let's make sure there is no trailing whitespace. There are ways to do this for each text editor.
+ examples/latent_space_model.py
  + add `#!/usr/bin/env python` to the top of the file. also add comments giving a brief explanation of the script; see the other example scripts as a reference
  + Following PEP8, `class Latent_Space_Model():` -> `class LatentSpaceModel:`
  + `self.num_vars` -> `self.n_vars`
  + remove commented out code
  + new data API
  + Following PEP8, only top-level functions and class definitions should be separated with two emptylines; everything else should be separated by one emptyline.
  + Let's push this into master now, along with `examples/data/celegans_brain.py`. In general, this pull request should not touch any files in the repo except for `docs/` and adding new directories.
+ examples/matrix_factorization.py
  + Same comments as above. Also, does this run? Or as you suggested, should we postpone adding this example until after this pull request?

__re:Authorship list in authors section and citation.__
I'm of the opinion that it should be sorted by order of joining, including only active developers, and with Dave second on the list. So at the moment, Dustin Tran, David M. Blei, Alp Kucukelbir, Adji Dieng, Maja Rudolph, and Dawen Liang. We can define an "active developer" in any way we want, e.g., loosely speaking, someone who has contributed to Edward in a big enough way and in the past year.  This encourages adding contributors not directly in our lab (it can be anyone), and it avoids the issue of Dave appended to a list of over 100 previous coauthors.

But I haven't thought carefully about all the issues around this. And while this is something we typically don't like to think about it, I think this is very important to address directly and transparently so we're all aware of the issues. Thoughts appreciated!

__re:Any text from `docs/` that was not improved or edited upon, but simply deleted.__ Let's move them all into the `edward-misc/` repo for now, so that we have them somewhere. For example, the getting started with TensorFlow page. Is there anything else?

**Comment by dustinvtran** [comment]
The full website is now ready https://rawgit.com/blei-lab/edward/doc/website/website/index.html

Planning to merge on Monday morning. Comments before then are much obliged!

**Comment by dustinvtran** [comment]
As a note of the related issues:

+ makes progress for #35; fixes #86; fixes #98; fixes #113; fixes #114; fixes #115; fixes #159; fixes #171

**Pull request merged**
