### PR TITLE
Make edward compatible with Tensorflow 0.12

### PR DESCRIPTION
**Pull request by gokceneraslan**
Initial attempt to add TF 0.12 compatibility. 

I have changed a few things in order to make edward compatible with TF 0.12:

- `tf.initialize_all_variables()` calls have been renamed to `tf.global_variables_initializer()`

- `tf.Variable.ref()` calls are removed. See: https://github.com/tensorflow/tensorflow/commit/c46f70c06985edce4905668a943801040c7a1354#diff-ae1a8f7b66539f000615a4ab7e4b2151R460. `ref()` is an internal function now.

- `tf.GraphKeys.VARIABLES` is replaced with `tf.GraphKeys.GLOBAL_VARIABLES`.

As a side note, even after applying these changes, edward still doesn't work because of the bug introduced in TF 0.12rc0, see: https://github.com/tensorflow/tensorflow/issues/5930 and https://github.com/tensorflow/tensorflow/commit/77cfa97ac784212130e97bc6fa9e6f8acfc86c08 for the fix. Therefore I had to use TF master branch.

There are still 2 test failing, I'm looking into them.

### CODE REVIEW

**Comment by gokceneraslan** [comment]
All test pass now. Travis will be happy after the release of TF `0.12rc1`.

**Comment by dustinvtran** [comment]
great work. i approve of all the changes. 

it's unfortunate that the users have to compile to master get eugene's fix working on the class inheritance. perhaps it makes sense for now to force all users to use version 0.11 for now, and wait until  0.12 (non-RC) is available before merging this in?

**Comment by gaika** [comment]
Please merge, it is pretty hard to find 0.11 binary, it has been removed from pip. Compiling 0.11 from source is just as hard as installing 0.12rc1

**Comment by gokceneraslan** [comment]
0.12rc1 does not have the fix, please use these 0.11 binaries for now:

https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#using-pip

**Comment by gaika** [comment]
Yeah, just figured it out, installed tensorflow from master, then checked out your fork, and then... half of the examples don't work :(

**Comment by gokceneraslan** [comment]
I rebased my branch on master to include 1.1.6 hotfix. You can re-clone (not pull) my branch and try again.

**Comment by dustinvtran** [comment]
thanks!

**Comment by stonebig** [comment]
no news ? Tensorflow-0.12.0 is out since Dec. 20th

**Comment by gokceneraslan** [comment]
This has to be fixed first: https://github.com/tensorflow/tensorflow/issues/5930.

**Comment by shoyer** [comment]
We are [rapidly moving toward TensorFlow 1.0](https://groups.google.com/a/tensorflow.org/d/topic/discuss/OePXmC9kJ7o/discussion). It might make sense to wait a little bit longer.

**Comment by rilut** [comment]
Hi, it seems that 1.0.0-alpha is now live and is the only one alpha that is planned. tensorflow/tensorflow#6570

**Comment by dustinvtran** [comment]
built off of in #426

**Pull request closed without merging**
