### PR TITLE
Feature/example mixture gaussian

### PR DESCRIPTION
**Pull request by dustinvtran**
#### Summary:

Issues: makes progress for #7, #22, #57

This adds an example of mixture modeling on synthetic data, using both mean-field variational inference and maximum a posteriori. For mean-field variational inference, the variational family is a product of Dirichlet, Gaussian, and Inverse Gamma densities. 

This also makes progress on how to build an interface allowing mean-field families that are a product of different distributions rather than only one distribution.

#### Intended Effect:

Mixture model examples are available.

#### How to Verify:

Run the new examples `mixture_gaussian.py` and `mixture_gaussian_map.py`. See that they work.

#### Side Effects:

N/A

#### Documentation:

Doc is added in the model examples.

#### Reviewer Suggestions: 

@diengadji

### CODE REVIEW

**Comment by dustinvtran** [comment]
I haven't done it yet, but it would great to add a custom `print_progress()` function in these examples. This would be similar to how the Bayesian linear regression examples show the distribution of lines converging around the points. Here, we can visualize the individual Gaussian components moving around and capturing the relevant data points during inference.

**Comment by dustinvtran** [comment]
@diengadji: I just finished an extension from this branch. It builds an abstraction so that we can specify variational families with arbitrary factors. Let's merge this pull request ASAP so we can get to discussing the cooler one. :)

**Comment by diengadji** [comment]
there is a divide by zero in the mixture_gaussian.py...the map works just fine

**Comment by fmpr** [comment]
Hi,

First of all, congratulations on developing edward!
I was looking into some of the examples and I think the mixture of gaussians example is not correct. 
Consider a simple mixture of 2 gaussians with joint probability:
`\prod_{n=1}^N ( \lambda \N(x|\mu_1,\sigma_1) + (1-\lambda) \N(x|\mu_2,\sigma_2) )`
Taking the log of this gives:
`\sum_{n=1}^N \log ( \lambda \N(x|\mu_1,\sigma_1) + (1-\lambda) \N(x|\mu_2,\sigma_2) )`
However, the example code is computing (correct me if I'm wrong...):
`\sum_{n=1}^N ( \log \lambda + \log \N(x|\mu_1,\sigma_1) + \log (1-\lambda) + \log \N(x|\mu_2,\sigma_2) )`
which is not the same thing. It completely bypasses the log-sum-exp issue, which makes things easier to compute, but then the results are wrong.

I did some tests with a very simple artificial dataset consisting of a mixture of two bi-dimensional gaussians with centers on [-1,-1] and [1,1]:

`def build_toy_dataset(N):

	pi = np.array([0.4, 0.6])
	mus = [[1,1],[-1,-1]]
	stds = [[0.1,0.1],[0.1,0.1]]
	x = []
	colors = cm.rainbow(np.linspace(0, 1, 2))
	for n in xrange(N):
		k = np.argmax(np.random.multinomial(1, pi))
		x.append(np.random.multivariate_normal(mus[k],np.diag(stds[k])))
		plt.scatter(x[n][0], x[n][1], color=colors[k])
	plt.show()
	return {'x': np.array(x).astype(np.float32)}`

The means inferred by the example code are completely off:
`mean: 
[ 0.48774096 -2.39035225 -1.22405362  0.62153614]`

I changed the log lik in the example code (naively) to be:

		log_lik = []
		n_samples = get_dims(zs[0])[0]
		for s in range(n_samples):
			log_lik_z = 0.0

			for k in range(self.K):
				result = tf.exp(norm.logpdf(x, mus[s, (k*self.D):((k+1)*self.D)], sigmas[s, (k*self.D):((k+1)*self.D)]))
				result = tf.matmul(result, tf.transpose(pi))
				result = tf.reduce_sum(result, 0)
				log_lik_z += tf.log(result)

			log_lik += [log_lik_z]

This seems to give results closer to the true means:
`[-0.83513373 -1.56447959  0.8101908   0.46021864]`
However, they are still a bit off, and this is not a very numerically stable way of computing log-sum-exps. I'm new to TensorFlow... Probably this could be done in a much better way... Any tips would be appreciated.

**Comment by XiaoSX** [comment]
import Error no module named edward.stats

**Comment by dustinvtran** [comment]
@XiaoSX | hi, this is an an old example that's no longer supported. I recommedn seeing http://edwardlib.org/tutorials/unsupervised.

**Comment by XiaoSX** [comment]
@dustinvtran Thanks, now the problem is that I got confused about the inference of the standard version of the mixture model (not collapsed one in tutorials), could you kindly do me a favor?

**Comment by dustinvtran** [comment]
It's worth working out alone as an exercise. As a hint, it should be the same as the collapsed version, only now you also define an approximating distribution for the mixture assignments too.

**Pull request merged**
