### PR TITLE
Feature/pep8 utilpy

### PR DESCRIPTION
**Pull request by akucukelbir**
#### Summary:

+ configures PEP8 according to TensorFlow style (2 spaces)
+ converts `util.py` to pass PEP8

#### Intended Effect:

See above.

#### How to Verify:

Look at code. Run tests.

#### Side Effects:

None.

#### Documentation:

None.

#### Reviewer Suggestions:

@dustinvtran

### CODE REVIEW

**Comment by akucukelbir** [comment]
hmm. how do we get travis to ignore `E111,E114`?

**Comment by akucukelbir** [comment]
okay. that works.

**Comment by dustinvtran** [comment]
So does this PR convert from 4-space to 2-space?

**Comment by akucukelbir** [comment]
yes. just for that file.

**Comment by dustinvtran** [comment]
I see. I was initially thinking we were going to do the 4-to-2 conversion all at once. Do you think incrementally is better?

**Comment by akucukelbir** [comment]
it's clear to look at the travis builds and see whether one (or a few)
file(s) has(have) passed the PEP8 test. (this includes the 4-to-2
conversion.)

so i think this is a good way to proceed forward.

**Comment by dustinvtran** [comment]
Yup that makes sense. Happy to merge this now. 

Can you rebase the commits as a single commit?

**Pull request closed without merging**
